baseURL = "http://blended-scala.org"
languageCode = "en-us"
title = "Blended - ZIO"
theme = "book"

enableGitInfo = true

[params]
  BookRepo = "https://github.com/blended-zio/blended-zio-site"
  GitCodeRibbon = "Fork me on Github"
  GitEditRibbon = "Edit me on Github"
  BookMenuBundle = "/menu"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    style = "manni"
    tabWidth = 2
