baseURL = "http://blended-scala.org"
languageCode = "en-us"
title = "Blended - ZIO"
theme = "book"

[params]
  BookMenuBundle = "/menu"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    style = "monokai"
    tabWidth = 2
