baseURL = "http://blended-scala.org"
languageCode = "en-us"
title = "Blended - ZIO"
theme = "book"

enableGitInfo = true

[params]
  BookRepo = "https://blended-zio@dev.azure.com/blended-zio/blended-zio/_git/blended-zio"
  GitRibbon = "Fork me on Azure"
  BookMenuBundle = "/menu"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    style = "manni"
    tabWidth = 2
